### ISSUE TITLE
Hi3559AV100 SDK for learn

### ISSUE THREAD

**Issue by Quato1985** [zhfeing/setup-HI3559A-tutorial#1]
Hi,

There is a chance to share the download link to HI3559AV100 SDK with me?

Thanks in advance :)

**Comment by zhfeing** [comment]
Hi, it‘s been quite a long time since I last use the SDK. 
Here are all the SDK I can find: 
https://pan.baidu.com/s/1VagFHSlYZRUyx28LAS97gQ
(extract code: `15rf`)

But unfortunately I can't remember which was exactly the one I used. You should try the latest version first, good luck :)
